# Generated by Django 2.0.4 on 2018-04-18 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_categoria', to='categorias.Categoria'),
        ),
        migrations.AlterField(
            model_name='eventocategoria',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_evento_categoria', to='eventos.Evento'),
        ),
    ]
