# Generated by Django 2.0.4 on 2018-04-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atletas', '0002_auto_20180417_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtletaClube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atletas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.Atleta')),
            ],
        ),
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='atletaclube',
            name='clube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Clube'),
        ),
    ]
