# Generated by Django 2.0.4 on 2018-04-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=17)),
                ('celular', models.CharField(max_length=17)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=17)),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nome',
        ),
        migrations.AddField(
            model_name='perfil',
            name='Vinculo',
            field=models.CharField(choices=[('Atleta', 'Atleta'), ('Tecnico', 'Tecnico'), ('Presidente do Clube', 'Presidente do Clube'), ('Presidente da Federação', 'Presidente da Federação'), ('Arbitro', 'Arbitro'), ('Gestor de eventos', 'Gestor de Eventos')], default='Atleta', max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='perfis.Pessoa'),
            preserve_default=False,
        ),
    ]
