# Generated by Django 2.0.4 on 2018-04-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_auto_20180418_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='Vinculo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil',
            field=models.CharField(choices=[('Atleta', 'Atleta'), ('Tecnico', 'Tecnico'), ('Presidente do Clube', 'Presidente do Clube'), ('Presidente da Federação', 'Presidente da Federação'), ('Arbitro', 'Arbitro'), ('Gestor de eventos', 'Gestor de Eventos')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
