# Generated by Django 2.0.4 on 2018-04-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Atleta',
            name='email',
        ),
        migrations.RemoveField(
            model_name='Atleta',
            name='name',
        ),
        migrations.RemoveField(
            model_name='Atleta',
            name='phone',
        ),
    ]
